<a href="https://colab.research.google.com/github/TanmayPriyadarshi/Coding_Blocks/blob/master/Numpy_Primer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# @Author --- Tanmay Priyadarshi
# @creation started on --- 21st January , 2020
# @creation ended on --- XXth January , 2020
# @Brief about Doc --- Basic and practical approach to know how things are done in Numpy.....
# @Title --- Numpy-Primer

# This document is all about giving you the quick introduction to the Numpy with respect to the it's usage in the data science.....

# I'll be going with the programming approach to grasp the concept we need in numpy

In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3,4,5])

In [0]:
print(a)

[1 2 3 4 5]


In [0]:
print(type(a))

<class 'numpy.ndarray'>


In [0]:
print(a.shape)

(5,)


# After seeing the result from a.shape you find yourself in confusing state....that the array we just created is having dimension as (1,5)....and mind it that you are bit on the right side but not entirely as the numpy work in bit different mannar . Remember array like a-which is just a collection of elements in linear or 1 line . In such case numpy print those array as a list that is horizontally while internally treat it as column matrix(having single vertical line which content element) therefore having multiple rows while having 1 column......remember that they don't even mention the number of column as 1 reason behind it is pretty sure that they want to make certain difference between 1-d array and multi-d array.....

In [0]:
b = np.array([[1],[2],[3],[4],[5]])

In [0]:
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [0]:
print(b.shape)

(5, 1)


# Now one question might have arised in your mind that how we are going to access the elements of the array?....solution to this question is pretty obvious that is using square brackets and index value.....just like if i want to access the 4 from above array then this is to the correct way to do so.....

In [0]:
print(b[3])

[4]


# The above code is returning the entire 4th row instead of single element that why it is surrounded by the square brackets....

# So in order to extract the only 4 from that array you need to use 2 square brackets...as that array is 2-d array...

In [0]:
print(b[3][0])

4


In [0]:
c = np.array([[1,2,3],[4,5,6]])

In [0]:
print(c)

[[1 2 3]
 [4 5 6]]


In [0]:
print(c.shape)

(2, 3)


# Now we are going to see the creation of some of the special type of the array or you can say matrix ....which will be directly used while dealing with the data science...

# All zero's matrix:----

In [0]:
z = np.zeros((3,3))

In [0]:
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
print(z.dtype)

float64


In [0]:
z1 = np.zeros((3,3),dtype = np.int64)

In [0]:
print(z1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [0]:
print(z.dtype)

float64


# All one' Matrix:----

In [0]:
b = np.ones((2,3))

In [0]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [0]:
print(b.dtype)

float64


# Matrix with special constant matrix:----

In [0]:
c = np.full((3,2),5)

In [0]:
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [0]:
print(c.dtype)

int64


In [0]:
c = np.full((3,2),5.0)

In [0]:
print(c)

[[5. 5.]
 [5. 5.]
 [5. 5.]]


In [0]:
print(c.dtype)

float64


# Indentity Matrix ---square matrix in nature:----

In [0]:
d = np.eye(4)

In [0]:
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [0]:
print(d.dtype)

float64


# Random matrix:----

In [0]:
rm = np.random.random((4,4))

In [0]:
print(rm)

[[0.33017323 0.98801894 0.93080262 0.74906463]
 [0.52817883 0.16165725 0.20771838 0.99960809]
 [0.41042356 0.14133703 0.07175676 0.63018793]
 [0.45390186 0.87021286 0.23405174 0.1524498 ]]


# Slicing operation or you can say selection or extraction operation has the same old methodology working for the numpy array also....which is likewise... 

# array-name[ indexing for 1st dimension, indexing for the 2nd dimension] while this indexing for the 1st and 2nd dimension further have 2 parts...i.e. starting index and ending index....but remember that starting is inclusive while ending is exclusive.....

# Now let us consider the scenario in which we have to print only 3rd row mid elements....then this will be your approach

In [0]:
print(rm[2:3,1:3])

[[0.14133703 0.07175676]]


# Now let's see how to set the value of some rows and columns with certain value:----

In [0]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
z[1,:] = 5

In [0]:
print(z)

[[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]


# Now as I've already discussed about data type i.e. dtype and how to change it? I think it doesn't need to be discussed any more in this practical based guide....

# Now let's see some of the mathematical operation that we can perform on the numpy array....and remember that the operation which I'm going to study is basically is element-wise mathematical operation and thus require the shape to be exactly the same in oder to keep the operation carried on...

In [0]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.random.random((2,3))

In [0]:
print(x)
print(y)
print(z)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[0.16889119 0.04813905 0.25903977]
 [0.36110031 0.57632487 0.9566749 ]]


In [0]:
print(x+y)

[[ 6  8]
 [10 12]]


In [0]:
print(x+z)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [0]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [0]:
print(np.add(x,z))

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [0]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


# This element-wise multiplication is having special name , called as Hadamard Product.....which I'll be discussing it later in this document.....for time being just remember the term name....

In [0]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [0]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [0]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
